#!/bin/bash

data_root=/media/dell/AAfMRI

for subj in 17 18; do

con=FH	

indir=$data_root/Results/Preprocessed/$subj/FH_Preprocessing/${subj}.pre.results
outdir=$data_root/Results/GLM/$subj/meanT1/${con}


con1=face
con2=house


stim_infor=$data_root/stim_information/${subj}
   
echo -----------------------------------${subj_id}-----------------------------------------------
   
   mkdir -p $outdir
   cd $outdir

 3dDeconvolve -input ${indir}/pb04.${subj}.pre.r01.scale+tlrc  \
   ${indir}/pb04.${subj}.pre.r02.scale+tlrc\
   ${indir}/pb04.${subj}.pre.r03.scale+tlrc\
   ${indir}/pb04.${subj}.pre.r04.scale+tlrc\
            -polort A \
           -num_stimts 8 \
           -stim_times 1 ${stim_infor}/${con1}.txt 'BLOCK(12,1)' -stim_label 1 ${con1} \
           -stim_times 2 ${stim_infor}/${con2}.txt 'BLOCK(12,1)' -stim_label 2 ${con2} \
           -stim_file 3 ${indir}/dfile_rall.1D'[0]' -stim_base 3 -stim_label 3 roll \
           -stim_file 4 ${indir}/dfile_rall.1D'[1]' -stim_base 4 -stim_label 4 pitch \
           -stim_file 5 ${indir}/dfile_rall.1D'[2]' -stim_base 5 -stim_label 5 yaw \
           -stim_file 6 ${indir}/dfile_rall.1D'[3]' -stim_base 6 -stim_label 6 ds \
           -stim_file 7 ${indir}/dfile_rall.1D'[4]' -stim_base 7 -stim_label 7 dl \
           -stim_file 8 ${indir}/dfile_rall.1D'[5]' -stim_base 8 -stim_label 8 dp \
           -censor ${indir}/motion_${subj}.pre_censor.1D \
           -gltsym "SYM: ${con1} -${con2}" -glt_label 1 F-H           \
           -iresp 1 ${con1} \
           -iresp 2 ${con2} \
           -fout -tout -full_first -x1D X_matrix.xmat.1D -fitts fitts_${con} -bucket ${subj}_${con}_bucket  \
           
           
 done 
 
 

 
 
 
 
 
 
 
