#!/bin/bash

data_root=/media/dell/AAfMRI
 
for subj in 17 18 {20..26} {28..32} ; do        ####  

   
indir=$data_root/RawData/${subj} 
outdir=$data_root/Results/Preprocessed/${con}/$subj


echo --///////////////////////////--${subj}////////////////////////////

   
   #rm -r $outdir
   mkdir -p $outdir
   cd $outdir 

   cat > run.afni_proc << EOF
       afni_proc.py                                            \
      -subj_id ${subj}                                         \
      -copy_anat ${indir}/${subj}_anat_ns+orig          \
      -anat_has_skull no                                       \
      -dsets $indir/R1.nii.gz $indir/R2.nii.gz                 \
      -blocks tshift align tlrc volreg blur mask scale regress    \
      -tshift_opts_ts -tpattern alt+z2                         \
      -radial_correlate_blocks tcat volreg                     \
      -tcat_remove_first_trs 0                                 \
      -align_opts_aea -cost lpc+ZZ -giant_move -check_flip       \
      -tlrc_base MNI152_T1_2009c+tlrc                         \
      -tlrc_NL_warp                                            \
      -volreg_align_to MIN_OUTLIER              \
      -volreg_align_e2a                          \
      -volreg_tlrc_warp                           \
      -volreg_warp_dxyz 3                          \           
      -mask_epi_anat yes                            \
      -blur_size 4.0                                 \
      -regress_censor_motion 0.3                   \                
      -regress_censor_outliers 0.1                  \
      -regress_make_ideal_sum sum_ideal.1D          \         
      -regress_est_blur_epits                       \
      -regress_est_blur_errts                        \
     -regress_apply_mot_types demean deriv            \
     -regress_run_clustsim no                          \
     -execute
EOF
tcsh run.afni_proc
done

